version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
          message: This is work in progress. Do not merge yet.
      - do: label
        no_empty:
          enabled: false
      - do: approvals
        min:
          count: 1
