repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "yarn lint"
        language: node
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.2" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
