version: '2.4'

x-env: &env
  GMO_COIN_API_KEY: &GMO_COIN_API_KEY ${GMO_COIN_API_KEY:?}
  GMO_COIN_SECRET_KEY: &GMO_COIN_SECRET_KEY ${GMO_COIN_SECRET_KEY:?}
  DATABASE_VOLUME: &DATABASE_VOLUME ${DATABASE_VOLUME:?}

  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "kaguya"
  build:
    context: .
  volumes:
    - .:/app

services:
  server:
    <<: *app
    command: bash -c 'wait-for-it db:5432 -- db-migrate up && kgy start'
    environment:
      <<: *env
    depends_on:
      - db


  db:
    image: "timescale/timescaledb:latest-pg13"
    volumes: 
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app

