version: "2.4"

x-env: &env
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN:-}
  GMO_COIN_API_KEY: &GMO_COIN_API_KEY ${GMO_COIN_API_KEY:-}
  GMO_COIN_SECRET_KEY: &GMO_COIN_SECRET_KEY ${GMO_COIN_SECRET_KEY:-}
  DATABASE_VOLUME: &DATABASE_VOLUME ${DATABASE_VOLUME:-./data/db}
  WEB_PORTL: &WEB_PORT ${WEB_PORT:-3000}
  NOTEBOOK_PORT: &NOTEBOOK_PORT ${NOTEBOOK_PORT:-8888}
  KABUSAPI_URL: &KABUSAPI_URL ${KABUSAPI_URL:-}
  KABUSAPI_WS_URL: &KABUSAPI_WS_URL ${KABUSAPI_WS_URL:-}
  KABUSAPI_PASSWORD: &KABUSAPI_PASSWORD ${KABUSAPI_PASSWORD:-}
  SCRIPT_SERVER_PORT: &SCRIPT_SERVER_PORT ${SCRIPT_SERVER_PORT:-5000}
  ENVIRONMENT: &ENVIRONMENT ${ENVIRONMENT:-local}

  # internal
  DATABASE_URL: postgres://app:app@db/app
  STORAGE_EMULATOR_HOST: storage:4443

x-app: &app
  image: "kgy"
  build:
    context: .
  volumes:
    - .:/app

services:
  db:
    image: "timescale/timescaledb:latest-pg13"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    volumes:
      - type: bind
        source: *DATABASE_VOLUME
        target: /var/lib/postgresql/data
    profiles:
      - production
      - development

  collector:
    <<: *app
    working_dir: /app/cli
    command: bash -c 'wait-for-it db:5432 -- kgy board collect'
    environment:
      <<: *env
    profiles:
      - production
    depends_on:
      - db
    restart: unless-stopped

  script-server:
    <<: *app
    environment:
      <<: *env
    command: ./start.sh
    working_dir: /app/script-server
    ports:
      - target: 5000
        published: *SCRIPT_SERVER_PORT
    profiles:
      - production
      - development

  storage:
    image: "fsouza/fake-gcs-server"
    volumes:
      - ./data/storage:/data/default
    command: -scheme http -port 4443
    profiles:
      - development

  app:
    <<: *app
    environment:
      <<: *env
    profiles:
      - development

  notebook:
    <<: *app
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --NotebookApp.password='' --NotebookApp.token='' --NotebookApp.notebook_dir='/app/notebook'
    ports:
      - target: 8888
        published: *NOTEBOOK_PORT
    profiles:
      - development
