version: "2.4"

x-env: &env
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN:-}
  GMO_COIN_API_KEY: &GMO_COIN_API_KEY ${GMO_COIN_API_KEY:-}
  GMO_COIN_SECRET_KEY: &GMO_COIN_SECRET_KEY ${GMO_COIN_SECRET_KEY:-}
  DATABASE_VOLUME: &DATABASE_VOLUME ${DATABASE_VOLUME:-./data/db}
  WEB_PORTL: &WEB_PORT ${WEB_PORT:-3000}

  # internal
  DATABASE_URL: postgres://app:app@db/app

x-app: &app
  image: "kaguya"
  build:
    context: .
  volumes:
    - .:/app

services:
  app:
    <<: *app
    environment:
      <<: *env

  collector:
    <<: *app
    working_dir: /app/cli
    command: bash -c 'wait-for-it db:5432 -- yarn db-migrate up && yarn cli start collector'
    environment:
      <<: *env
    depends_on:
      - db

  api:
    <<: *app
    working_dir: /app/cli
    command: bash -c 'wait-for-it db:5432 -- yarn db-migrate up && yarn cli start api'
    environment:
      <<: *env
    depends_on:
      - db

  web:
    <<: *app
    working_dir: /app/web
    command: yarn dev
    environment:
      <<: *env
    ports:
      - target: 3000
        published: *WEB_PORT
    depends_on:
      - api

  db:
    image: "timescale/timescaledb:latest-pg13"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    volumes:
      - type: bind
        source: *DATABASE_VOLUME
        target: /var/lib/postgresql/data
