version: '2.4'

x-env: &env
  GMO_COIN_API_KEY: &GMO_COIN_API_KEY ${GMO_COIN_API_KEY}
  GMO_COIN_SECRET_KEY: &GMO_COIN_SECRET_KEY ${GMO_COIN_SECRET_KEY}

  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "kaguya"
  build:
    context: .
  volumes:
    - .:/app

services:
  server:
    <<: *app
    command: kgy start
    environment:
      <<: *env


  db:
    image: "timescale/timescaledb:latest-pg13"
    volumes: 
      - ./db-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app

