version: '2.4'

x-env: &env
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN}
  GMO_COIN_API_KEY: &GMO_COIN_API_KEY ${GMO_COIN_API_KEY}
  GMO_COIN_SECRET_KEY: &GMO_COIN_SECRET_KEY ${GMO_COIN_SECRET_KEY}


  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "kaguya-dev"
  build:
    context: .
  volumes:
    - .:/app


services:
  app:
    <<: *app
    environment:
      <<: *env

  db:
    image: "timescale/timescaledb:latest-pg13"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
