version: '2.4'

x-env: &env
  CODECOV_TOKEN: &CODECOV_TOKEN ${CODECOV_TOKEN}
  GMO_COIN_API_KEY: &GMO_COIN_API_KEY ${GMO_COIN_API_KEY}
  GMO_COIN_SECRET_KEY: &GMO_COIN_SECRET_KEY ${GMO_COIN_SECRET_KEY}


  # internal
  DATABASE_URL: postgres://app:app@db/app


x-app: &app
  image: "kaguya"
  build:
    context: .
  volumes:
    - .:/app


services:
  app:
    <<: *app
    environment:
      <<: *env


  server:
    <<: *app
    command: bash -c 'wait-for-it db:5432 -- db-migrate up && kgy start'
    environment:
      <<: *env
    depends_on:
      - db
  db:
    image: "timescale/timescaledb:latest-pg13"
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
    volumes: 
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
