version: 2

jobs:
  build_and_test:
    machine:
      image: ubuntu-2004:202107-02
      resource_class: large
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: "Setup environment variables"
          command: |
            echo 'export COMPOSE_FILE=docker-compose.yaml' >> $BASH_ENV

      - restore_cache:
          keys:
            - docker-image-{{ .Environment.CACHE_VERSION }}-{{ checksum "Dockerfile" }}-{{ checksum "kaguya_nn/setup.py" }}


      - run:
          name: "Build images if needed"
          command: |
            if test -f image.tar; then
              docker load < image.tar
            else
              docker-compose build app
              docker save kaguya-dev > image.tar
            fi

      - save_cache:
          key: docker-image-{{ .Environment.CACHE_VERSION }}-{{ checksum "Dockerfile" }}-{{ checksum "kaguya_nn/setup.py" }}
          paths:
            - ./image.tar



      - restore_cache:
          keys:
            - node-modules-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install node modules if needed
          command: |
            if [ ! -d node_modules ]; then
              docker-compose run --rm app yarn install  --frozen-lockfile
            fi

      - save_cache:
          key: node-modules-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./packages/core/node_modules
            - ./packages/server/node_modules
            - ./packages/api/node_modules
            - ./packages/web/node_modules

      - run:
          name: Setup services
          command: |
            docker-compose up -d db

      - run:
          name: Lint
          command: |
            docker-compose run --rm -w /app/kaguya_nn app mypy
            docker-compose run --rm -w /app/core app yarn tsc
            docker-compose run --rm -w /app/server app yarn tsc

      - run:
          name: Test db migrate
          command: |
            docker-compose run --rm app wait-for-it db:5432 -- yarn db-migrate up

      - run:
          name: Test
          command: |
            docker-compose run --rm -w /app/server app yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
